# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian-squeeze"
  # config.vm.box_url = "http://domain.com/path/to/above.box"
  config.vm.network :forwarded_port, guest: 5432, host: 5432
  config.vm.provision :shell, :path => "blank-box-init"
end
